version: "3"

services:
  postgis:
    # do not upgrade until you can install postgresql-client on the
    # esida container with the same version! Otherwise pg_dump/pg_resotre
    # will not work for dumping/importing database.
    image: postgis/postgis:14-3.3
    environment:
      POSTGRES_DB: esida
      POSTGRES_USER: esida
      POSTGRES_PASSWORD: esida
      PGDATA: /var/lib/postgresql/data/pgdat
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  esida:
    build: .
    environment:
      POSTGIS_HOST: postgis
      POSTGIS_DB: esida
      POSTGIS_USER: esida
      POSTGIS_PASS: esida
      POSTGIS_PORT: 5432
      FLASK_BASIC_AUTH_FORCE: "False"
    ports:
      - 80:80
    volumes:
      - ./:/app/
  # Jupyter Hub wit lot's of gis dependencies installed
  jupyter:
    image: gboeing/osmnx:latest
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/work

